src/deno/stable/functions.ts, src/deno/stable/functions/sleepSync.ts, src/deno/stable/variables/ppid.ts
Resolves #14.
The underlying problem was from https://github.com/denoland/deno/issues/10827. Because there was a type vs implementation disparity upstream, we had imitated it in deno.ns. Since upstream is fixed, ppid is now stable, and sleepSync is unstable. I've removed the import for sleepSync in this PR. We can add it back if/when upstream sleepSync is stable, or remove it if Deno does too.
I tried to add support for unstable imports, but this breaks because stable and unstable `lib.deno.d.ts` cause conflicts. This is in a branch if you want to check it out: https://github.com/MKRhere/deno.ns/tree/feat-unstable-deno, and I'm not sure if/how to tackle this yet. We can discuss this in a different issue if we evaluate that unstable is necessary.
Signed-off-by: Muthu Kumar …
=> fix: Deno.ppid & Deno.sleepSync

package.json, src/deno/internal/version.ts, src/deno/stable/variables/version.ts, tools/denolib.ts
`npm run denolib` will now write the current version along with lib.deno.d.ts
Signed-off-by: Muthu Kumar <muthukumar@thefeathers.in>
=> Write version along with denolib

.github/workflows/ci.yml
The master branch seems renamed to main branch and CI is not running on main now. This PR tries to fix it.
=> chore: update ci branch name

lib/deno.ns.lib.d.ts, package-lock.json, package.json, src/index.ts, tools/generateDeclarationFile.ts
I didn't exactly fix this last time around because it didn't work for constructor types (ex. `new Headers()`). It's hard to add unit tests for this, so I've tested it manually downstream.
=> fix(types): fix constructor types for global fallback types

.vscode/project.code-workspace, package.json, packages/deno.ns/src/util/mod.ts, packages/shim-timers/LICENSE, packages/shim-timers/README.md, packages/shim-timers/package.json, packages/shim-timers/src/index.ts, packages/shim-timers/tsconfig.json
Creates a `@deno/shim-timers` package that provides compatible `setTimeout` and `setInterval` functions.
This package will be used by dnt for shims for these two functions.
=> feat: add `@deno/shim-timers` package

.vscode/project.code-workspace, README.md, deno.json, package.json, packages/shim-crypto/LICENSE, packages/shim-crypto/README.md, packages/shim-crypto/package.json, packages/shim-crypto/src/index.ts, packages/shim-crypto/tsconfig.json
I know this seems kind of useless at the moment, but in the future this will also include polyfills for some of the missing webcrypto functionality that Node doesn't have.
=> feat: add `@deno/shim-crypto` package

packages/shim-crypto/package.json, packages/shim-crypto/scripts/generateCryptoTypes.ts, packages/shim-crypto/src/crypto.types.gen.ts, packages/shim-crypto/src/index.ts
This PR fixes the web crypto types by extracting out the crypto types from lib.dom.d.ts and bundling them in the shim.
This is necessary because DefinitelyTyped does not provide types for web crypto at the current time. It is true that not all node web crypto functions will be supported and doing this might hide that during type checking... it will be up to users of the shim to test their usages to ensure they work.
=> fix(crypto): generate crypto types

packages/shim-deno/src/deno/stable/classes/PermissionStatus.ts
Trying to make tests pass on Node 14 (#77) proved difficult. This non-breaking change makes them at least run.
=> Shim `EventTarget` to support Node 14

.vscode/project.code-workspace, README.md, deno.json, package-lock.json, package.json, packages/sham-weakref/LICENSE, packages/sham-weakref/README.md, packages/sham-weakref/package.json, packages/sham-weakref/src/index.test.ts, packages/sham-weakref/src/index.ts, packages/sham-weakref/tsconfig.json, packages/shim-timers/src/index.test.ts
This packages provides a sham (not a shim) for `WeakRef`. It will use `globalThis.WeakRef` if it exists though.
=> feat: add `@deno/sham-weakref` package

.github/workflows/ci.yml
Closes #77. Closes #15.
The step I replaced could never fail.
`npm publish` step seems unused.
Since there isn't a pre-commit hook anymore, https://github.com/denoland/node_deno_shims/blob/aa22b201add21509bea5effe7fd59128b4ade32b/packages/shim-deno/tools/missing.ts#L36-L42 slows down `tools/missing.ts` for no benefit.
=> chore: ensure that `shim-deno` runs (not necessarily correctly) on Node 14

packages/shim-deno/src/deno/internal/fs_flags.ts, packages/shim-deno/src/deno/stable/functions/create.ts
Hi. I'm working on using dnt on our project, [pbkit](https://github.com/pbkit/pbkit)
I noticed that the shim of Deno.create always throw an exception because the flag option on `create` doesn't have `write` option.
So I fixed it by adding `write` option and the wrong error message too.
Thanks for your contribution on dnt and this project!
=> fix(shim-deno/create): Fix wrong OpenOptions on Deno.create

packages/shim-deno/src/deno/stable/functions/lstat.ts, packages/shim-deno/src/deno/stable/functions/stat.ts
I wrapped `lstat`, `stat` with `mapError` to convert node error to deno one instead of using `[Symbol.hasInstance]
`
resolves #94
=> Wrap with mapError to catch Deno.errors.NotFound correctly

packages/shim-deno/src/deno/stable/variables/std.ts
If node's "process" module is imported, accessing stdin by `fs.read` throws `EAGAIN` error: resource temporarily unavailable.
So I re-implemented std interface using `process.stdin`, `process.stdout`, `process.stderr`.
resolves #97
=> fix(shim-deno/std): Fix std not to use FsFile

.github/workflows/ci.yml, README.md
- Git repo having submodules are rare, in my case I did not clone submodules, and the errors received, did not help much.
- I try first with a local deno 1.29 and the build failed, I rolled back my deno to 1.28.3 to match the `startsWith('1.28')` in the code, but that failed too... so add a `deno upgrade --version 1.28.1` in the readme should help, some people.
Closes #125
=> docs: update Contributing section in main readme + patch GitHub action

packages/shim-deno/src/deno/stable/variables/std.ts, packages/shim-deno/tools/run_tests.mjs
Fixes #146. I had to add some conditions to fix the tests, because otherwise I was getting the following error, I think newer node sets globalThis.crypto as a getter-only, so when it does exist in node, it'll break in this test:
```js
globalThis.crypto = (await import("node:crypto")).webcrypto;
^
TypeError: Cannot set property crypto of #<Object> which has only a getter
```
=> feat: implement Deno.stdin.readSync, Deno.stdout.writeSync, bugfix shims

packages/shim-deno/PROGRESS.md, packages/shim-deno/lib/shim-deno.lib.d.ts, packages/shim-deno/src/deno/stable/functions.ts, packages/shim-deno/src/deno/stable/functions/addSignalListener.ts, packages/shim-deno/src/deno/stable/functions/removeSignalListener.ts, packages/shim-deno/tools/denolib.ts
I need some input on this idea.
Since Node.js and Deno have different signal types, I modified the declaration of Deno.Signal to be, essentially, `Deno.Signal & NodeJS.Signals`, preventing us from translating "Deno-only signals" to Node.js.
I tried finding out exactly which signals that mismatch, but I think that might depend on the platform/arch you built the binary on, not sure. On _my_ machine, `SIGEMT` is the only Deno signal that does not exist in Node.js. `SIGIOT`, `SIGPOLL`, `SIGUNUSED`, `SIGXFSZ`, and `SIGLOST` exist in Node.js, but not in Deno.
Additionally, in Node.js, `process.addListener` returns the NodeJS.Process object itself, whereas in Deno, `Deno.addSignalListener` returns void, so I figured it would only make sense for the translated Node.js code returns void as well. …
=> feat: addSignalListener, removeSignalListener

packages/shim-deno/lib/shim-deno.lib.d.ts, packages/shim-deno/package.json, packages/shim-deno/src/deno/internal/version.ts, packages/shim-deno/tools/generateDeclarationFile.ts
The declaration file should be right beside the `index.js` file.
=> fix(shim/deno): correct types

packages/shim-prompts/src/readlineSync.ts
Something in the internals of fs.readSync changed at some point, which causes the following error if you provide an offset integer to readSync while reading stdin:
`ESPIPE: invalid seek, read`
Solution is to not provide additional arguments, as [the defaults are equivalent](https://nodejs.org/api/fs.html#fsreadsyncfd-buffer-options) for this usecase.
Tested on Debian 11 and Windows 10
Closes #158
=> fix: update readSync to not provide seek / offset parameters

packages/shim-prompts/src/index.ts
Removes an extra space in the prompt, adds the default `message`, and fixes the logic to match the Deno implementation.
I compared it to https://github.com/denoland/deno/blob/main/runtime/js/41_prompt.js#L33-L50, correct me if this is the wrong place please!
The main part of the Deno implementation looks like this:
https://github.com/denoland/deno/blob/a4ec7dfae01485290af91c62c1ce17a742dcb104/runtime/js/41_prompt.js#L34-L44
```ts
defaultValue ??= null;
if (!isatty(stdin.rid)) {
return null;
}
if (defaultValue) {
message += ` [${defaultValue}]`;
}
message += " ";
```
`defaultValue` is assigned to `null` if `defaultValue` is `undefined` or `null` (see [nullish coalescing assignment (??=)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignmen …
=> fix: match Deno version of `prompt`

packages/shim-deno/lib/shim-deno.lib.d.ts, packages/shim-deno/src/deno/stable/functions/consoleSize.ts
Add shim for `Deno.consoleSize()`
https://deno.land/api@v1.39.0?s=Deno.consoleSize
=> feat: add shim for Deno.consoleSize()

packages/shim-deno/src/deno/stable/functions/consoleSize.ts
Addition to https://github.com/denoland/node_shims/pull/165
=> fix: Deno.consoleSize should handle if stdout is piped

.github/workflows/ci.yml, packages/shim-deno/src/deno/stable/classes/PermissionStatus.ts, packages/shim-deno/src/deno/stable/variables/mainModule.ts
Node 14 has been end of life for over a year and it's highly recommended to migrate away from it. If you need Node 14 support, please use `@deno/shim-deno` 0.18.2.
=> refactor(BREAKING): drop Node 14 support

packages/shim-deno/src/deno/stable/variables/build.ts
Not perfect, but better.
Closes #152
=> fix: `Deno.build.arch` should be aarch64 for aarch64

packages/shim-deno/src/deno/stable/variables/mainModule.test.ts, packages/shim-deno/src/deno/stable/variables/mainModule.ts, packages/shim-deno/tools/working_test_files.txt
It was accidentally using code as if written in Deno.
=> fix: correct mainModule code
